server:
  port: ${SERVER_PORT:9090}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/light}
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

openapi:
  service:
    title: Light digital API application
    version: 1.0.0

secret:
  key: ${SECRET_KEY:7A2621BBAC3FF47E4BF95EFEB6F8B89442568DB55A7EECAB12CA45FF32}