CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    username VARCHAR NOT NULL ,
    password VARCHAR NOT NULL ,
    role VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS organizations (
    organization_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    inn VARCHAR NOT NULL ,
    title VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS organization_admins (
    admin_id BIGINT NOT NULL ,
    organization_id BIGINT NOT NULL ,
    PRIMARY KEY (admin_id, organization_id),
    CONSTRAINT fk_admin_organization_admins FOREIGN KEY (admin_id) REFERENCES users(user_id),
    CONSTRAINT fk_organization_organization_admins FOREIGN KEY (organization_id)
        REFERENCES organizations(organization_id)
);

CREATE TABLE IF NOT EXISTS documents (
    document_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    number UUID NOT NULL ,
    status VARCHAR NOT NULL ,
    customer_id BIGINT NOT NULL ,
    organization_id BIGINT NOT NULL ,
    CONSTRAINT fk_customer_document FOREIGN KEY (customer_id) REFERENCES users(user_id) ,
    CONSTRAINT fk_organization_document FOREIGN KEY (organization_id) REFERENCES organizations(organization_id)
);

CREATE TABLE IF NOT EXISTS document_requests (
    document_request_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    status VARCHAR NOT NULL ,
    customer_id BIGINT NOT NULL ,
    organization_id BIGINT NOT NULL ,
    CONSTRAINT fk_customer_document_request FOREIGN KEY (customer_id) REFERENCES users(user_id) ,
    CONSTRAINT fk_organization_document_request FOREIGN KEY (organization_id) REFERENCES organizations(organization_id)
);

CREATE TABLE IF NOT EXISTS events (
    event_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    title VARCHAR NOT NULL ,
    price FLOAT NOT NULL ,
    min_age INT NOT NULL ,
    author_id BIGINT NOT NULL ,
    CONSTRAINT fk_author_event FOREIGN KEY (author_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS event_requests (
    event_request_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    fullname VARCHAR NOT NULL ,
    age INT NOT NULL ,
    pcr BOOLEAN NOT NULL ,
    status VARCHAR NOT NULL ,
    author_id BIGINT NOT NULL ,
    event_id BIGINT NOT NULL ,
    CONSTRAINT fk_author_event_requests FOREIGN KEY (author_id)
        REFERENCES users(user_id) ,
    CONSTRAINT fk_event_event_requests FOREIGN KEY (event_id)
        REFERENCES events(event_id)
);